<link href="/assets/css/login.css" rel="stylesheet">

<div class="container text-center">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <h2>Faça seu Login</h2>

                <form class="d-flex flex-column align-items-center gap-2" action="/login" method="POST">
                    <div>
                        <label class="form-label" for="email">Email:</label>
                        <input class="form-control" type="email" id="email" name="email" required>
                    </div>
                    <div>
                        <label class="form-label" for="password">Senha:</label>
                        <input class="form-control" type="password" id="password" name="password" required>
                    </div>
                    <div>
                        <button class="btn btn-success mt-2" type="submit">Entrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>