name: Continous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Generate Codeception files
        run: ./run codecept build

      - name: Setup Uploads assets permissions
        run: sudo chown -R www-data:www-data public/assets/uploads

      - name: Up containers
        run: ./run up -d

      - name: PHPUnit Units test
        run: ./run test tests/Unit

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Clean Codeception cache
        run: rm -rf tests/Support/_generated/*

      - name: Generate Codeception files
        run: ./run codecept build
      
      - name: Verify test files
        run: |
          echo "=== PublicCest.php ==="
          cat tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== HomeIndexCest.php ==="
          cat tests/Acceptance/home/HomeIndexCest.php
          echo ""
          echo "=== AuthCest.php (lines 70-80) ==="
          sed -n '70,80p' tests/Acceptance/auth/AuthCest.php

      - name: Down containers (clean start)
        run: ./run down -v || true

      - name: Remove all Docker volumes
        run: docker volume prune -f || true

      - name: Up containers
        run: ./run up -d --build --force-recreate

      - name: Clear all PHP caches inside container
        run: |
          docker exec flashwise-php_test-1 php -r "if (function_exists('opcache_reset')) opcache_reset();" || echo "No opcache"
          docker exec flashwise-php_test-1 rm -rf /var/www/tests/Support/_generated/*
          docker exec flashwise-php_test-1 ./vendor/bin/codecept build

      - name: See containers
        run: ./run ps

      - name: Verify code inside container
        run: |
          echo "=== PublicCest.php completo ==="
          docker exec flashwise-php_test-1 cat /var/www/tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== HomeIndexCest.php completo ==="
          docker exec flashwise-php_test-1 cat /var/www/tests/Acceptance/home/HomeIndexCest.php
          echo ""
          echo "=== AuthCest.php linhas 10-60 ==="
          docker exec flashwise-php_test-1 sed -n '10,60p' /var/www/tests/Acceptance/auth/AuthCest.php
          echo ""
          echo "=== Verificando cache Codeception ==="
          docker exec flashwise-php_test-1 ls -la /var/www/tests/Support/_generated/
          echo ""
          echo "=== Verificando se há opcache ==="
          docker exec flashwise-php_test-1 php -i | grep opcache || echo "Opcache não habilitado"

      - name: PHPUnit Acceptance test
        run: ./run test:browser

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: Generate Codeception files
        run: ./run codecept build

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan
