name: Continous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Generate Codeception files
        run: ./run codecept build

      - name: Setup Uploads assets permissions
        run: sudo chown -R www-data:www-data public/assets/uploads

      - name: Up containers
        run: ./run up -d

      - name: PHPUnit Units test
        run: ./run test tests/Unit

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Clean Codeception cache
        run: rm -rf tests/Support/_generated/*

      - name: Generate Codeception files
        run: ./run codecept build
      
      - name: Verify test files
        run: |
          echo "=== PublicCest.php ==="
          cat tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== HomeIndexCest.php ==="
          cat tests/Acceptance/home/HomeIndexCest.php
          echo ""
          echo "=== AuthCest.php (lines 70-80) ==="
          sed -n '70,80p' tests/Acceptance/auth/AuthCest.php

      - name: Down containers (clean start)
        run: ./run down -v || true

      - name: Remove all Docker volumes
        run: docker volume prune -f || true

      - name: Up containers
        run: ./run up -d --build --force-recreate

      - name: Clear all PHP caches inside container
        run: |
          echo "Limpando cache PHP opcache..."
          docker exec flashwise-php_test-1 sh -c 'php -r "if (function_exists(\"opcache_reset\")) { opcache_reset(); echo \"Opcache cleared\n\"; } else { echo \"No opcache\n\"; }"' || echo "Falha ao limpar opcache"
          echo ""
          echo "Removendo arquivos _generated do Codeception..."
          docker exec flashwise-php_test-1 rm -rf /var/www/tests/Support/_generated/*
          echo "Arquivos _generated removidos"
          echo ""
          echo "Reconstruindo Codeception..."
          docker exec flashwise-php_test-1 /var/www/vendor/bin/codecept build
          echo "Codeception reconstruído"

      - name: See containers
        run: ./run ps

      - name: Verify code inside container
        run: |
          echo "=== PublicCest.php COMPLETO (workspace) ===" 
          cat tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== PublicCest.php COMPLETO (container) ==="
          docker exec flashwise-php_test-1 cat /var/www/tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== MD5 comparison ==="
          echo -n "Workspace MD5: "
          md5sum tests/Acceptance/access/PublicCest.php | cut -d' ' -f1
          echo -n "Container MD5: "
          docker exec flashwise-php_test-1 md5sum /var/www/tests/Acceptance/access/PublicCest.php | cut -d' ' -f1
          echo ""
          echo "=== HomeIndexCest.php COMPLETO (container) ==="
          docker exec flashwise-php_test-1 cat /var/www/tests/Acceptance/home/HomeIndexCest.php
          echo ""
          echo "=== AuthCest.php completo (container) ==="
          docker exec flashwise-php_test-1 cat /var/www/tests/Acceptance/auth/AuthCest.php
          echo ""
          echo "=== Verificando cache Codeception ==="
          docker exec flashwise-php_test-1 ls -la /var/www/tests/Support/_generated/ || echo "Diretório vazio ou não existe"
          echo ""
          echo "=== Verificando opcache status ==="
          docker exec flashwise-php_test-1 php -i | grep -i "opcache.enable" || echo "Opcache config not found"

      - name: PHPUnit Acceptance test
        run: ./run test:browser

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: Generate Codeception files
        run: ./run codecept build

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan
