name: Continuous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Generate Codeception files
        run: ./run codecept build

      - name: Up containers
        run: ./run up -d

      - name: Wait for containers to be ready
        run: sleep 15

      - name: PHPUnit Units test
        run: ./run test tests/Unit

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Clean Codeception cache
        run: rm -rf tests/Support/_generated/*

      - name: Generate Codeception files
        run: ./run codecept build

      - name: Down containers (clean start)
        run: ./run down -v || true

      - name: Remove all Docker volumes
        run: docker volume prune -f || true

      - name: Up containers with fresh build
        run: ./run up -d --build --force-recreate

      - name: Wait for all services to be ready
        run: sleep 20

      - name: Check container status
        run: ./run ps

      - name: Run Codeception Acceptance Tests
        run: ./run test:browser

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Run PHPStan
        run: ./run composer phpstan

      - name: Run PHP CS Fixer (dry-run)
        run: ./run composer cs-fix-dry-run