name: Continous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Generate Codeception files
        run: ./run codecept build

      - name: Setup Uploads assets permissions
        run: sudo chown -R www-data:www-data public/assets/uploads

      - name: Up containers
        run: ./run up -d

      - name: PHPUnit Units test
        run: ./run test tests/Unit

  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Clean Codeception cache
        run: rm -rf tests/Support/_generated/*

      - name: Generate Codeception files
        run: ./run codecept build
      
      - name: Verify test files
        run: |
          echo "=== PublicCest.php ==="
          cat tests/Acceptance/access/PublicCest.php
          echo ""
          echo "=== HomeIndexCest.php ==="
          cat tests/Acceptance/home/HomeIndexCest.php
          echo ""
          echo "=== AuthCest.php (lines 70-80) ==="
          sed -n '70,80p' tests/Acceptance/auth/AuthCest.php

      - name: Down containers (clean start)
        run: ./run down || true

      - name: Up containers
        run: ./run up -d --build

      - name: See containers
        run: ./run ps

      - name: PHPUnit Acceptance test
        run: ./run test:browser

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: Generate Codeception files
        run: ./run codecept build

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan
