<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flash Wise</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="/assets/css/application.css" rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">
    <header>
        <?php
        require __DIR__ . '../../partials/header.phtml';
        ?>
    </header>
    <main class="flex-grow-1 mt-5">

        <?php require '_flash_message.phtml'; ?>



        <?php require $view ?>
    </main>
    <footer>
        <?php
        require __DIR__ . '../../partials/footer.phtml';
        ?>
    </footer>
</body>

</html>