<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlashWise - Sistema de Flashcards</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="/assets/css/variables.css">

    <link rel="stylesheet" href="/assets/css/application.css">
    <link rel="stylesheet" href="/assets/css/components.css">
    <link rel="stylesheet" href="/assets/css/animations.css">
    <link rel="stylesheet" href="/assets/css/paginator.css">

    <link rel="stylesheet" href="/assets/css/home.css">

    <link rel="stylesheet" href="/assets/css/header.css">
    <link rel="stylesheet" href="/assets/css/footer.css">

    <link rel="stylesheet" href="/assets/css/login.css">

    <link rel="stylesheet" href="/assets/css/decks.css">
    <link rel="stylesheet" href="/assets/css/deck-form.css">
    <link rel="stylesheet" href="/assets/css/deck-details.css">
    <link rel="stylesheet" href="/assets/css/deck-edit.css">

    <link rel="stylesheet" href="/assets/css/card-form.css">
</head>

<body class="d-flex flex-column min-vh-100">
    <?php require 'partials/header.phtml'; ?>

    <div class="container mt-3">
        <?php require '_flash_message.phtml'; ?>
    </div>

    <main class="flex-grow-1">
        <?php require $view ?>
    </main>

    <?php require  'partials/footer.phtml'; ?>
</body>

</html>